version: "3.8"

services:
  # mysqldb:
  #   image: mysql:5.7
  #   restart: unless-stopped
  #   env_file: ./.env
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
  #     - MYSQL_DATABASE=$MYSQLDB_DATABASE
  #   networks:
  #     - dentnet
  #   ports:
  #     - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
  #   volumes:
  #     - db:/var/lib/mysql
  app:
    # depends_on:
    #   - mysqldb
    # --기존 container db와 연결할 경우 external_links
    # external_links:
    #   - mariadb
    image: yknam/kikisequelize
    container_name: kikisequelize
    build: ./.
    restart: unless-stopped
    env_file: ./.env
    networks:
      - kong-net
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    #environment:
      # --docker와 연결할 경우
      # - DB_HOST=mariadb
      # --local mariadb와 연결할 경우
      # - DB_HOST=$DB_HOST
      # - DB_USER=$DB_USER
      # - DB_PASSWORD=$DB_PASSWORD
      # - DB_NAME=$DB_NAME
      # - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true
# volumes:
#     maria-data:
#         name: maria-data
#     db:
networks:
    kong-net:
        driver: bridge
        name: kong-net
